# Generated by Django 4.1.3 on 2022-12-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterModelManagers(
            name="movie",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="email",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="password",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="username",
        ),
    ]
