# Generated by Django 4.1.3 on 2022-12-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_options_alter_movie_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="user_permissions",
            new_name="user",
        ),
    ]
