# Generated by Django 4.1.3 on 2022-12-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movieorder_movie_alter_movieorder_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="movie_orders",
            new_name="orders",
        ),
    ]
